version: "3.8"
volumes:
  db-store:
services:
  db:
    build:
      context: .
      dockerfile: ./docker/mysql/Dockerfile
    env_file:
      - .env
    ports:
      - target: 3306
        published: ${DB_PORT:-3306}
        protocol: tcp
        mode: host
    volumes:
      - type: volume
        source: db-store
        target: /var/lib/mysql
        volume:
          nocopy: true
      - type: bind
        source: ./docker/mysql/init
        target: /docker-entrypoint-initdb.d
    environment:
      - MYSQL_DATABASE=${DB_NAME}
      - MYSQL_USER=${DB_USER}
      - MYSQL_PASSWORD=${DB_PASS}
      - MYSQL_ROOT_PASSWORD=${DB_PASS}
      # TODO Redis
      # - SESSION_DRIVER=${SESSION_DRIVER}
      # - SESSION_LIFETIME=${SESSION_LIFETIME:-120}
      # - REDIS_HOST=cache
      # - REDIS_PASSWORD=null
      # - REDIS_PORT=6379
    expose:
      - 3306
  web:
    build:
      context: .
      dockerfile: ./docker/go/Dockerfile
      target: dev
    tty: true
    stdin_open: true
    volumes:
      - ./:/go/app
    command: air
    ports:
      - "8080:8080"
      - "2345:2345"
    # Docker上で delveを利用する為の設定
    security_opt:
      - apparmor:unconfined
    # Docker上で delveを利用する為の設定
    cap_add:
      - SYS_PTRACE
    depends_on:
      - db